### ISSUE TITLE
get-esm-packages not listing any packages

### ISSUE THREAD

**Issue by MoSattler** [kiliman/rmx-cli#8]
when running
```bash
npx rmx-cli get-esm-packages "@visx/scale"
```

It doesn't give me the list of esm packages, even though it depends on d3, [which is famously a causing problem esm package](https://github.com/remix-run/remix/discussions/2686).

**Comment by kiliman** [comment]
Fixed in v0.3.5

**Comment by MoSattler** [comment]
@kiliman 
It is still happening for me when running it without specifying a package. E.g. 
```
npx rmx-cli get-esm-packages
```

**Comment by kiliman** [comment]
That's not currently supported. You still need to supply the initial ESM package. It finds all the ESM dependencies of that package. 

Perhaps I'll update it to scan all the packages in your project's package.json.

**Comment by MoSattler** [comment]
ah okay, got it. Maybe it makes sense to show an error when no package name is provided instead of providing an empty list.

**Comment by DevanB** [comment]
> That's not currently supported. You still need to supply the initial ESM package. It finds all the ESM dependencies of that package.
> 
> Perhaps I'll update it to scan all the packages in your project's package.json.

We have a hand-built solution right now that checks all packages in the project's package.json right now. We use that output to create a json file that we then use the remix.config.js, like so:

```
const esmPackages = require("./esm-packages.json")

/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverDependenciesToBundle: [
    ...esmPackages
  ],
  serverBuildTarget: "vercel",
  // When running locally in development mode, we use the built in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  sourceMap: process.env.NODE_ENV === "development",
  ignoredRouteFiles: [".*"]
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "api/index.js",
  // publicPath: "/build/",
};
```

 Would be neat to see this handy utility do that and optionally spit out a json file or something.
